version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=chat-support
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password

    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat-support
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: redis:7.0.8
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass password

volumes:
  db-data:
  redis-data:
